app:
  kafka:
    # If Kafka is running in a cluster then it's possible to provide comma (,) separated addresses.
    # For example: localhost:9091,localhost:9092
    broker-address: broker:9092
    rest-proxy-url: http://rest-proxy:8082
    # Defines the Kafka client that the adapter uses: restProxyClient or tcpClient.
    client-qualifier: restProxyClient
  cache:
    # The length of time in seconds after an entry is last accessed that it should be automatically removed
    duration: 600